### ISSUE TITLE
# noqa not honored for most Errors

### ISSUE THREAD

**Issue by stchris** [PyCQA/pep8#180]
Quoting from https://bitbucket.org/tarek/flake8/issue/37/pep8-doesnt-honor-noqa: " Only the E501 (line length) and the E12* (continuation line) benefit from this feature.", while "# noqa" should work on all kinds of errors and warnings.

Example: 
```python
a = 1
if a == None:  # noqa
  pass
```

**Comment by jayvdb** [comment]
For indirect use of pep8 via flake8, there is an extension which provides this (by fiddling with the default flake8 reporter, so it only works with jobs = 1):
https://pypi.python.org/pypi/flake8-respect-noqa

I have built a flake8 extension which provides per-file and per-line configuration out of the source tree, by fiddling with the `ignore_code` part of the error reporting (and thus even more hacky, but works with jobs > 1): https://github.com/jayvdb/flake8-putty

**Comment by galsondor** [comment]
I want to reinforce @cbeland's point.  There are many cases where columnar alignment provides more clarity than strict compliance with whitespace rules.

Reading the comments above, the primary argument against broad application of #noqa is the addition of noise in the source code&mdash;a real concern.  Another real concern is overuse of global suppression (e.g., via setup.cfg).  Many programmers use Eclipse and other IDEs configured to show PEP 8 warnings all the time.  (After all, keeping code PEP 8 compliant is usually easier than fixing it later.)  However, if global suppression is avoided and local suppression not available, the _noise_ created within the IDE becomes a problem.

This situation is compounded on team projects.  The only practical team approach to PEP 8 warnings is elimination of all warnings.  Without local suppression, global suppression is the only option&mdash;and global suppression leads to missed problems.

Please enable suppressing all rules, or at least the whitespace rules (and E221 in particular),with #noqa.  PEP 8 is the [standard for the Python Standard Library](https://www.python.org/dev/peps/pep-0008/#introduction).  For all other products, let's leave suppression decisions to the product team.

**Comment by IanLee1521** [comment]
Closing, see call for pull requests in #480.
