### ISSUE TITLE
E129 strange issue

### ISSUE THREAD

**Issue by AndrewPashkin** [PyCQA/pep8#295]
With given code:
```
# coding=utf-8

if (a == b and
    c <= d * 60 and
    h.method_call('whatever')):
        return True
```

and version `1.5.7`, 
the module throws:
```
E129 visually indented line with same indent as next logical line
```
And this code is accepted:
```
if (a == b and
        c <= d * 60 and
        h.method_call('whatever')):
        return True
```
But it is clear that first version is better.

**Comment by mikeecb** [comment]
if (a == b and
            c <= d * 60):
        return True

The code above seems to not throw any errors. It looks like pep8 allows the following:

    # No extra indentation.
    if (this_is_one_thing and
        that_is_another_thing):
        do_something()

    # Add a comment, which will provide some distinction in editors
    # supporting syntax highlighting.
    if (this_is_one_thing and
        that_is_another_thing):
        # Since both conditions are true, we can frobnicate.
        do_something()

    # Add some extra indentation on the conditional continuation line.
    if (this_is_one_thing
            and that_is_another_thing):
        do_something()

So the original issue shouldn't produce an error.

**Comment by sigmavirus24** [comment]
E129 was split from E125 to specifically allow it to be ignored on its own. Closing this as a result.
