### ISSUE TITLE
`E129 visually indented line with same indent as next logical line`

### ISSUE THREAD

**Issue by llllllllll** [PyCQA/pep8#386]
This error does not follow PEP 8's recommendations. Consider the code:

```python
 if (a and
     b):
     c
```

running `pep8` yields:

```
a.py:2:5: E129 visually indented line with same indent as next logical line
    b):
    ^
```

The relevant part of PEP 8 that I am referencing is:

> When the conditional part of an if -statement is long enough to require that it be written across multiple lines, it's worth noting that the combination of a two character keyword (i.e. if ), plus a single space, plus an opening parenthesis creates a natural 4-space indent for the subsequent lines of the multiline conditional. This can produce a visual conflict with the indented suite of code nested inside the if -statement, which would also naturally be indented to 4 spaces. This PEP takes no explicit position on how (or whether) to further visually distinguish such conditional lines from the nested suite inside the if -statement. Acceptable options in this situation include, but are not limited to:

```python
# No extra indentation.
if (this_is_one_thing and
    that_is_another_thing):
    do_something()

# Add a comment, which will provide some distinction in editors
# supporting syntax highlighting.
if (this_is_one_thing and
    that_is_another_thing):
    # Since both conditions are true, we can frobnicate.
    do_something()

# Add some extra indentation on the conditional continuation line.
if (this_is_one_thing
        and that_is_another_thing):
    do_something()
```

**Comment by myint** [comment]
This is mentioned in #126.

**Comment by sigmavirus24** [comment]
As @myint points out, E129 was specifically split from E125 to allow it to be ignored and disabled. Closing this since it's a small rule that you can turn off if you disagree with it.

**Comment by snoack** [comment]
Since PEP-8 allows this style of indentation, I think people should not have to explicitly ignore E129, but should rather have to explicitly opt-in in order to get E129 errors.

**Comment by gandhis1** [comment]
I would concur...can't emphasize the number of times Ive had to refactor my if statements just to please the linter.

**Comment by dagwieers** [comment]
Both E129 as well as W503 (line break before binary operator) are confusing if PEP8 recommends it for breaking long conditions. It seems you can't win if line-length and arbitrary rules are fighting to get enforced but conflicting.
