### ISSUE TITLE
Support python -m pep8

### ISSUE THREAD

**Issue by coderanger** [PyCQA/pep8#416]
Would be nice for tooling if you could run via `python -m pep8`.

**Comment by sigmavirus24** [comment]
Yeah this allows the tooling to ignore what's in the `PATH` and such, right?

The trick is that `pep8` has always been a single-file which allows people to just download and use it as if it were a one-off script/tooling.

If this is something the @PyCQA/pep8-core developers want to support, what we could do is:

1. Create a `pep8` module with the appropriate `__init__.py` and `__main__.py` submodules.
2. Move `pep8.py` into `pep8/`
3. Symlink `pep8/pep8.py` (or whatever we would name that file) to `pep8.py`

We would then slightly change how we distribute pep8, but we would preserve backwards compatibility in case people have scripts to auto-update/download pep8 from GitHub. (FWIW, GitHub will redirect them to this organization page and the symlink should Just Work™)

**Comment by sigmavirus24** [comment]
So this actually already works. @dstufft pointed out that this is already supported and I was able to confirm this. I have pep8 installed globally on my laptop and if I do

```
$ python -m pep8
```

In a directory with code I get the output as I would expect. Have you found a situation where this doesn't work?

**Comment by coderanger** [comment]
I could have sworn I tested this and got an error but I'm betting I was using the wrong Python binary. Sorry for the noise!

**Comment by sigmavirus24** [comment]
No worries!
