### ISSUE TITLE
Using --ignore envokes E226 error

### ISSUE THREAD

**Issue by mFoxRU** [PyCQA/pep8#439]
Consider the following code:
```
print 1 + (2+3)

``` 
Running `$ pep8 file.py` gives no error. But adding `--ignore=` with any code gives:
`file.py:1:14: E226 missing whitespace around arithmetic operator`

**Comment by sigmavirus24** [comment]
By specifying your own ignore, you're overriding the [`DEFAULT_IGNORE`](https://github.com/PyCQA/pep8/blob/master/pep8.py#L68) that pep8 uses. This is expected (and, if I remember correctly, documented) behaviour.
