### ISSUE TITLE
pep8 not detecting E225?

### ISSUE THREAD

**Issue by ChillarAnand** [PyCQA/pep8#441]
Original issue: https://github.com/hhatto/autopep8/issues/219

```
$ cat test.py
x = 'foo'[0:  2]

$ pep8 test.py 
```

It is not detecting whitespace around slice operator.

**Comment by sigmavirus24** [comment]
What version of pep8 are you using?

**Comment by myint** [comment]
This looks kind of like #321.

**Comment by sigmavirus24** [comment]
Good catch @myint
