### ISSUE TITLE
Allow custom indentation levels.

### ISSUE THREAD

**Issue by msjaiswal** [PyCQA/pep8#449]
In my company the practice is to use 2 tabs instead of 4 tabs as prescribed by pep8 guidelines. It's probably not a good idea to force the whole organisation to switch to 4 spaces convention.

How about if we were able to give a custom indentation multiple. For example: "--indentation-multiple 2". pep8 will do everything it does along except it will consider 2 as correct indentation instead of 4.

**Comment by sigmavirus24** [comment]
This is a duplicate of #389 

*Please check open and closed issues before filing bugs or feature requests.*
