### ISSUE TITLE
Create a new release

### ISSUE THREAD

**Issue by chrisseto** [PyCQA/pep8#451]
A new release should be create so projects using newer versions of python can use pep8

**Comment by toddrme2178** [comment]
This would be very much appreciated.  I am doing packaging for openSUSE, and this combined with the now-fixed incompatibility with flake8 is holding up a couple dozen packages from building under Python 3.5.

**Comment by sigmavirus24** [comment]
As someone who cannot perform a release and as the maintainer of Flake8, releases should only be made when they're ready and when the project is in a state where it's most beneficial to the users. Releasing anything other than the best release possible at the time is doing a disservice. Outside pressure should not play a role in whether or not the project administrators choose to release a new version of pep8.

**Comment by IanLee1521** [comment]
Closed with #470

**Comment by Tarrasch** [comment]
I experience that E731 and E402 was added as of this release (but I didn't see any mention in the release logs). Could that be correct? Here is an example python project that had to make some changes because (I think) this release made pep8 checking slightly stricter. https://github.com/spotify/luigi/pull/1504/

**Comment by sigmavirus24** [comment]
@Tarrasch those were changed in 1.6.X not in 1.7.0. They have been around for a while. If you're getting pep8 through flake8 then they're new to you because flake8 did not support the 1.6 series.

**Comment by Tarrasch** [comment]
You are correct about we using flake8. Thanks for the clarification @sigmavirus24. =)
