### ISSUE TITLE
Check for file encoding definition

### ISSUE THREAD

**Issue by pkess** [PyCQA/pep8#461]
To ensure cross-platform compatibility one should add a line like
```
# -*- coding: utf-8 -*-
```
in your python source file. Is there any way to check if this definition exists?

**Comment by sigmavirus24** [comment]
We try to limit the number of items checked for to cases called out specifically in [PEP-0008](https://www.python.org/dev/peps/pep-0008/). That isn't so we have no check for that. You could easily write an extension for that with Flake8 that checks for the existence of a `coding:` line at the start of a file.
