### ISSUE TITLE
Missing Google Style Guide recommendation for strings

### ISSUE THREAD

**Issue by traxair** [PyCQA/pep8#462]
I went through the issues to make sure this have never been discussed, and I'm fairly sure it hasn't.

I have inconsistent quotes in my repository (both " and ') and I wanted to clean this up. This is consistent with the [Google Style Guide](https://google.github.io/styleguide/pyguide.html#Strings), which states: _Be consistent with your choice of string quote character within a file. Pick ' or " and stick with it. It is okay to use the other quote character on a string to avoid the need to \ escape within the string._

I was thinking we could count the number of `"` and `'`, and issue an error on the one that was least used. An exception case should be made (ie, the surrounding quote should not be counted) when there is at least one `'` between two `"` and vice-versa.

There is a corner case on strings that are split over several lines for line-length such as:
```python
my_string = ("I don't like using double quotes"
             "but sometimes I have to")
```

Here the second line would be considered as wrong, but it makes sense visually that it should have the same quotes as the one above. I guess the same case can be made for any character between two strings (be it `\` [I think there is a separate rule to impede that], `\n`, `\r\n`, `+`).

Anyway, what do you think of this extra rule?

**Comment by sigmavirus24** [comment]
This project does not implement the Google Style Guide. Where the two overlap is merely coincidence. [hacking](/openstack-dev/hacking) implements a lot of the Google style guide as a plugin to flake8 though.

Alternatively, you could develop this as your own flake8 plugin and distribute that as well. That would be welcome in the PyCQA if you wanted to create the project and publish it before moving it there.

**Comment by traxair** [comment]
Thanks!
