### ISSUE TITLE
Allow for exceptions for E402

### ISSUE THREAD

**Issue by hynek** [PyCQA/pep8#472]
Hi,
in tests I have quite frequently something like:

``` python
import pytest

pytest.importorskip("twisted")

from twisted.internet.defer import Deferred, succeed, fail

from internal_package import xyz
```

which now reports `E402`s.

Any chance you add an exception for that? The annoying part is that I’d have to add `noqa`s to every single import statement that comes after the `importorskip()` which would also hamper with unused symbols detection…

By itself I find `E402` useful so I don’t want to suppress it either…

**Comment by jayvdb** [comment]
One improvement would be for `pytest.importorskip("twisted")  # noqa` to mean all the following imports do not need a `noqa`.

**Comment by IanLee1521** [comment]
It seems like a better way might be to have your test code checked with something like `pep8 --ignore=E402 tests/`

**Comment by hynek** [comment]
As I wrote I like E402 so I would prefer to not silence it altogether...

Since it seems to support the try/except idiom, I thought this could be added too.  

But I could live with putting `noqa` on the non-import line too.

**Comment by alasdairnicol** [comment]
It's a similar issue when writing [standalone scripts][1] that use Django

    import django
    from django.conf import settings
    from myapp import myapp_defaults

    settings.configure(default_settings=myapp_defaults, DEBUG=True)
    django.setup()

    # Now this script or any imported module can use any part of Django it needs.
    from my_app import models
    from my_other_app import models

I'd find it useful to be able to add #noqa to the `settings.configure` and `django.setup()` lines, as @jayvdb suggested.

[1]: https://docs.djangoproject.com/en/1.9/topics/settings/#calling-django-setup-is-required-for-standalone-django-usage

**Comment by IanLee1521** [comment]
Closing, see call for pull requests in #480.

**Comment by ashb** [comment]
If anyone comes across this issue and would like a fix that doesn't involve noqa on each line, nor to globally disable it, I wrote https://pypi.org/project/flake8-pytest-importorskip/ to handle it "automatically".

**Comment by asottile** [comment]
> 
> 
> If anyone comes across this issue and would like a fix that doesn't involve noqa on each line, nor to globally disable it, I wrote https://pypi.org/project/flake8-pytest-importorskip/ to handle it "automatically".

I would not recommend that plugin -- it uses private implementation detail that will break in a future version of `flake8`: https://github.com/ashb/flake8-pytest-importorskip/blob/6d2e6fb03ce5f938ae555b6f5e930637af3454fe/flake8_pytest_importorskip/__init__.py#L9

**Comment by ashb** [comment]
Yes -- it's a hack. It works for now though.

**Comment by asottile** [comment]
> Yes -- it's a hack. It works for now though.
> 
> > It does this in a slightly hacky way, so it may break in future versions of flake8 or pycodestyle.

ah, well as the flake8 maintainer -- I plan to change that bit of code so it likely will not work in the future :)

**Comment by ashb** [comment]
@asottile If you are changing that, would it be possible to have a plugin change the logical_line that "later plugins" see?

**Comment by asottile** [comment]
I really don't think that's a good idea -- lying about the source code to other plugins.  plus there's not really a concept of plugin ordering (that your plugin works at all right now is dumb ordering luck)

**Comment by ashb** [comment]
I thought ordering was alphabetic - guess just got lucky.

**Comment by ashb** [comment]
As for Lying to other plugins: http://pylint.pycqa.org/en/latest/how_tos/transform_plugins.html 😀

**Comment by asottile** [comment]
pylint's system is more for augmenting existing information (giving hints to pylint's engine about information it can't glean statically) -- I don't see how you'd implement your bait-and-switch with a non-import line to an import given that without severely breaking other things

**Comment by ashb** [comment]
Yeah, I wasn't being serious anyway. Another perhaps less hacky approach would be to let warnings get filtered by other plugins before being issued.

I also have another idea that might work that doesn't need me to look at private state -- I might be able to monkey patch the other plugin function, to wrap it.
