### ISSUE TITLE
E129 is wrong and misleading

### ISSUE THREAD

**Issue by ramnes** [PyCQA/pep8#474]
E129 is a misleading error for valid PEP8 code, as seen on other issues (#126, #295, #386 and maybe more). Hence, I wonder what's its real purpose.

`pep8` is a widely used tool that people use to validate their code against PEP8, not an other quality standard; I feel like it has to stay as close as possible from the original document, and shouldn't add more rules than decided by the Python community itself on the PEP.

I know I can disable it, but I don't think it's sufficient. I would suggest to disable it by default or to simply remove it.

As a reminder, here's [what PEP8 says](https://www.python.org/dev/peps/pep-0008/#indentation
):
> When the conditional part of an if -statement is long enough to require that it be written across multiple lines, it's worth noting that the combination of a two character keyword (i.e. if ), plus a single space, plus an opening parenthesis creates a natural 4-space indent for the subsequent lines of the multiline conditional. This can produce a visual conflict with the indented suite of code nested inside the if -statement, which would also naturally be indented to 4 spaces. **This PEP takes no explicit position on how (or whether) to further visually distinguish such conditional lines from the nested suite inside the if -statement. Acceptable options in this situation include, but are not limited to**:
```python
> # No extra indentation.
> if (this_is_one_thing and
>     that_is_another_thing):
>     do_something()
```
> [...]

**Comment by sigmavirus24** [comment]
Please understand that the document is frequently updated and this particular section that you've emphasized was written after E129 was created. Also, this tool is being rebranded to avoid any further confusion of its checks with PEP-0008 the document.

Cheers

**Comment by ramnes** [comment]
I don't really understand your point. If PEP8 has been updated to accept that practice, why wouldn't you make this tool compliant?

About the re-branding, that will indeed "solve" the problem, even if I find it a bit sad. Thanks for pointing this to me thought, I didn't see #466 and will follow that thread.

**Comment by sigmavirus24** [comment]
> even if I find it a bit sad

Complain to the people complaining about the name ;)

> If PEP8 has been updated to accept that practice, why wouldn't you make this tool compliant?

We add very few checks per minor release and try to disable very few by default. If we keep shifting checks into disabled by default or on by default and adding new checks, we're making the tool actively user-hostile. When people run pep8/pycodestyle/flake8 in their CI to check for style consistency and your example code stops returning a warning when people are expecting it to (and feel that the style pycodestyle is enforcing is better) then you're being actively hostile towards your users.

We also, are a maintenance team that wants to focus on improving the tool rather than keeping up with the constant (and usually contradictory) changes being made to PEP-0008. In that sense, the re-branding gives us a lot of room to breathe. We won't have people constantly creating duplicate issues for new pieces added to the text (or old pieces being removed, etc.).

**Comment by ramnes** [comment]
> Complain to the people complaining about the name ;)

:innocent:

I'm not really complaining about the name, actually! I find it great to have a tool called `pep8` that check every explicit rule defined on PEP8 (in opposition to #466), and the whole point of my issue was precisely to make it a bit more compliant.

> We add very few checks per minor release and try to disable very few by default. If we keep shifting checks into disabled by default or on by default and adding new checks, we're making the tool actively user-hostile. When people run pep8/pycodestyle/flake8 in their CI to check for style consistency and your example code stops returning a warning when people are expecting it to (and feel that the style pycodestyle is enforcing is better) then you're being actively hostile towards your users.

That makes a lot of sense, indeed. Though, versions could be used to handle compatibility. I would never expect `pep8` to throw me the same errors on version 1 and version 2.
 
> We also, are a maintenance team that wants to focus on improving the tool rather than keeping up with the constant (and usually contradictory) changes being made to PEP-0008. In that sense, the re-branding gives us a lot of room to breathe. We won't have people constantly creating duplicate issues for new pieces added to the text (or old pieces being removed, etc.).

I fully understand, and I definitely agree that you should rename the tool if you want to keep that focus.

Thanks for your explanations and time.

**Comment by sigmavirus24** [comment]
> I'm not really complaining about the name, actually! 

I know. You seemed sad that we're renaming the project though. As you can tell, I pointed out the flaws in the pseudo-legal threats in that message. I'm not a fan of the rename either but it is beneficial to several groups (including the PEP authors/maintainers who have always been fairly adversarial with respect to the existence of this tool).
