### ISSUE TITLE
What does "noqa" mean?

### ISSUE THREAD

**Issue by gvanrossum** [PyCQA/pep8#476]
This may be frivolous, but I don't know where else to ask, and Google searches aren't helpful... Does anyone here remember the etymology of "noqa"?

**Comment by sigmavirus24** [comment]
It used to be "nopep8" but when Flake8 and Pep8 wanted a common qualifier @florentx suggested "NoQA" as in "No Quality Assurance" (iirc) and it stuck.

**Comment by gvanrossum** [comment]
Ah, so it *does* mean "No Q/A" for the usual meaning of Q/A in software development. Thanks!

**Comment by maximveksler** [comment]
What's the actual meaning? For ex what does it stand for here https://github.com/pandas-dev/pandas/blob/master/pandas/tests/io/test_parquet.py#L16

**Comment by sigmavirus24** [comment]
@maximveksler https://github.com/PyCQA/pycodestyle/issues/476#issuecomment-179553820

**Comment by hoylemd** [comment]
@maximveksler It makes flake8 and pycodestyle (nee pep8) ignore errors on that line

**Comment by jkryanchou** [comment]
I have searched for a while but get nothing correct description on the word.

**Comment by gvanrossum** [comment]
The answer is above in https://github.com/PyCQA/pycodestyle/issues/476#issuecomment-179553820
