### ISSUE TITLE
Docs on read the docs are not up to date

### ISSUE THREAD

**Issue by alasdairnicol** [PyCQA/pep8#478]
The docs on Read The Docs (i.e. http://pep8.readthedocs.org/) appear to be out of date. The latest version seems to be 1.6.2, not the current version 1.7.0.

I hope it's ok to report this issue here, since it's about the hosting of the docs, not the code itself.

**Comment by IanLee1521** [comment]
Hmm.. I just checked and it looks like they are the 1.7 docs. For example, the [changes](http://pep8.readthedocs.org/en/latest/developer.html#changes) listed on the "latest" build are for 1.7.0.

Are there particular pages you think are wrong?

It is possible that latest (which is the default on RTF) has changes *newer* than 1.7 which you might be seeing?

**Comment by alasdairnicol** [comment]
Thanks for the quick reply. I think the problem was that there hadn't been any changes to `/docs/` since 1.7 was released. When you have merged #479 today, it triggered a build of the docs, and now I can see the docs for 1.7.

**Comment by IanLee1521** [comment]
ah, got it. Well if you notice any issues like that again... Let me know!

**Comment by sigmavirus24** [comment]
@alasdairnicol I'm fairly certain that is *not* how ReadTheDocs works. It should build for every change that's pushed to master. It could have been a problem with the move pep8 undertook into this organization though.

**Comment by IanLee1521** [comment]
I have seen issues with RTF falling out of sync. I agree @sigmavirus24 that it *shouldn't* work that way though. Can't recall if this was an issue before or after the migration, but let's just keep an eye on it.

**Comment by alasdairnicol** [comment]
If you look at the [list of builds][1], you can see that there were not any builds for 5 months before today. 

I think that builds [3734278](https://readthedocs.org/projects/pep8/builds/3734278/), [3734279](https://readthedocs.org/projects/pep8/builds/3734279/), and [3734280](https://readthedocs.org/projects/pep8/builds/3734280/) were triggered after my pull request was merged today. The two most recent ones [3735575](https://readthedocs.org/projects/pep8/builds/3735575/) and [3735576](https://readthedocs.org/projects/pep8/builds/3735576/) were me by accident when I was exploring the read the docs website this evening.

@sigmavirus24 I didn't realise that it was meant to build for all pushes to master. In that case, I don't have any other suggestions about why the docs were not rebuilt until today.

[1]: https://readthedocs.org/projects/pep8/builds/

**Comment by IanLee1521** [comment]
Hm, so as of 20:15 PST, I pushed a change which has "Triggered" a build, that hasn't completed... https://readthedocs.org/projects/pep8/builds/

I'll keep an eye on it to see, might be an issue with RTF?
